### ISSUE TITLE
The "Plugin" page was blank in v3.0.1, but v3.0.0 was fine.

### ISSUE THREAD

**Issue by wdhwang** [apache/apisix-dashboard#2782]
### Issue description

I used the same procedures to create apisix-dashboard v3.0.0 and v3.0.1 docker images via apisix-docker project. The only difference is APISIX_DASHBOARD_TAG's value. When I started the v3.0.1 image, and click the 'Plugin' function from the left menu. I can see the correct layout displayed, but after a very short time (maybe 0.3 sec) the screen became empty. Nothing displayed on the screen. If I viewed the source code from browser by click mouse left button, I could see js codes.

### Expected behavior

[
![PluginPage](https://user-images.githubusercontent.com/10345015/228420222-10fb1f1c-0a39-42ce-856f-9116b17ec2fa.png)

### How to Reproduce

1. git clone https://github.com/apache/apisix-docker.git
2. cd apisix-docker/dashboard
3. Modify Dockerfile.alpine, and set ARG APISIX_DASHBOARD_TAG=v3.0.1
4. docker build -t apisix-dashboard:dev -f Dockerfile.alpine ./
5. push the built image to DockerHub in my personal account
6. helm show values apisix/apisix-dashboard > values.yaml
7. Modify values.yaml, and change image repository to my built image
8. helm install apisix-dashboard apisix/apisix-dashboard -n apisix -f values.yaml
9. you may try to click 'Plugin' page

### Environment

- apisix version (cmd: `apisix version`): Image: apache/apisix:3.0.0-debian
- OS (cmd: `uname -a`): Image: alpine:latest
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`): 
- etcd version, if have (cmd: run `etcd --version`):  Image: docker.io/bitnami/etcd:3.5.4-debian-11-r14
- apisix-dashboard version, if have: v3.0.1
- Browser version, if have: Chrome  111.0.5563.112

**Comment by Baoyuantop** [comment]
Are there any JavaScript error messages in the browser console?

**Comment by wdhwang** [comment]
There are no error message at all. You may check the video to know how it happens.
https://user-images.githubusercontent.com/10345015/228707808-71324980-e2fd-4d90-9111-a75bc04caca5.mp4

**Comment by yoke233** [comment]
goto url `plugin/market`

show some plugins quickly then they disappear and the page got blank

dashboard_version | 3.0.0


```

﻿
umi.cdcf4f80.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
p__Plugin__List.c1fae2a6.async.js:1 
 Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
p__Plugin__List.c1fae2a6.async.js:1 
 You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker
29
109.5c8c6f3a.async.js:1 
 Error: Unexpected usage
    at e.value (p__Plugin__List.c1fa…6.async.js:1:482931)
    at p__Plugin__List.c1fa…6.async.js:1:496298
p__Route__List.0efb348d.async.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
p__Route__List.0efb348d.async.js:1 
Object
web-client-content-script.js:1 
 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at web-client-content-script.js:1:281387
    at Array.every (<anonymous>)
    at web-client-content-script.js:1:281359
umi.cdcf4f80.js:1 
 TypeError: Cannot read properties of undefined (reading 'disable')
    at p__Plugin__PluginMar….async.js:1:3664285
    at Array.filter (<anonymous>)
    at p__Plugin__PluginMar….async.js:1:3664176
    at _l (umi.cdcf4f80.js:1:1548033)
    at Kc (umi.cdcf4f80.js:1:1567239)
    at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
    at li (umi.cdcf4f80.js:1:1509384)
    at Wc (umi.cdcf4f80.js:1:1566990)
    at Cc (umi.cdcf4f80.js:1:1558536)
    at umi.cdcf4f80.js:1:1509675
p__Plugin__PluginMar…187e4219.async.js:1 
 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disable')
    at p__Plugin__PluginMar….async.js:1:3664285
    at Array.filter (<anonymous>)
    at p__Plugin__PluginMar….async.js:1:3664176
    at _l (umi.cdcf4f80.js:1:1548033)
    at Kc (umi.cdcf4f80.js:1:1567239)
    at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
    at li (umi.cdcf4f80.js:1:1509384)
    at Wc (umi.cdcf4f80.js:1:1566990)
    at Cc (umi.cdcf4f80.js:1:1558536)
    at umi.cdcf4f80.js:1:1509675
```

**Comment by SkyeYoung** [comment]
It seems that there are some errors in the processing of 'disable'.

**Comment by caibirdme** [comment]
blank page also encountered in v3.0.0/plugin module.

**Comment by caibirdme** [comment]
/routes/{id}/edit page could still be blank after I manually remove the _meta field in route config. Here's what admin api returns:
```json
{
    "createdIndex":285,
    "key":"/apisix/routes/454780323129983877",
    "modifiedIndex":290,
    "value":{
        "id":"454780323129983877",
        "name":"checkopenid",
        "upstream":{
            "type":"roundrobin",
            "ignore other fields": "to make it simple"
        },
        "status":1,
        "create_time":1680599796,
        "host":"api.example.com",
        "uri":"/user/checkopenid",
        "plugins":{
            "forward-auth":{
                "client_headers":[],
                "uri":"http://172.18.63.2:12312/auth",
                "upstream_headers":[],
                "request_headers":[]
            },
            "proxy-rewrite":{
                "scheme":"http"
            }
        },
        "methods":[
            "POST"
        ]
    }
}
```

Here's the err from web console:
```
umi.cdcf4f80.js:1 
        
       TypeError: Cannot read properties of undefined (reading 'disable')
    at p__Route__Create.ad1ba13e.async.js:1:5053535
    at Array.filter (<anonymous>)
    at p__Route__Create.ad1ba13e.async.js:1:5053426
    at _l (umi.cdcf4f80.js:1:1548033)
    at Kc (umi.cdcf4f80.js:1:1567239)
    at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
    at li (umi.cdcf4f80.js:1:1509384)
    at Wc (umi.cdcf4f80.js:1:1566990)
    at Cc (umi.cdcf4f80.js:1:1558536)
    at umi.cdcf4f80.js:1:1509675

p__Route__Create.ad1ba13e.async.js:1 
        
       Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disable')
    at p__Route__Create.ad1ba13e.async.js:1:5053535
    at Array.filter (<anonymous>)
    at p__Route__Create.ad1ba13e.async.js:1:5053426
    at _l (umi.cdcf4f80.js:1:1548033)
    at Kc (umi.cdcf4f80.js:1:1567239)
    at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
    at li (umi.cdcf4f80.js:1:1509384)
    at Wc (umi.cdcf4f80.js:1:1566990)
    at Cc (umi.cdcf4f80.js:1:1558536)
    at umi.cdcf4f80.js:1:1509675
```

**Comment by caibirdme** [comment]
After removing `{_meta: {disable: false}}` manually from the route config, the `/route/{id}/edit` page also becomes blank.
Here's my conf get from admin api:
```json
{
    "createdIndex":285,
    "key":"/apisix/routes/454780323129983877",
    "modifiedIndex":290,
    "value":{
        "id":"454780323129983877",
        "update_time":1680755250,
        "name":"checkopenid",
        "upstream":{
            "ignore to make it simple": "xx"
        },
        "status":1,
        "create_time":1680599796,
        "host":"api.example.com",
        "uri":"/user/checkopenid",
        "plugins":{
            "forward-auth":{
                "client_headers":[],
                "uri":"http://172.18.63.2:12312/auth/game",
                "upstream_headers":[],
                "request_headers":[]
            },
            "proxy-rewrite":{
                "scheme":"http"
            }
        },
        "methods":[
            "POST"
        ]
    }
}
``` 
And here's error from browser:
```
umi.cdcf4f80.js:1 
        
       TypeError: Cannot read properties of undefined (reading 'disable')
    at p__Route__Create.ad1ba13e.async.js:1:5053535
    at Array.filter (<anonymous>)
    at p__Route__Create.ad1ba13e.async.js:1:5053426
    at _l (umi.cdcf4f80.js:1:1548033)
    at Kc (umi.cdcf4f80.js:1:1567239)
    at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
    at li (umi.cdcf4f80.js:1:1509384)
    at Wc (umi.cdcf4f80.js:1:1566990)
    at Cc (umi.cdcf4f80.js:1:1558536)
    at umi.cdcf4f80.js:1:1509675

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disable')
    at p__Route__Create.ad1ba13e.async.js:1:5053535
    at Array.filter (<anonymous>)
    at p__Route__Create.ad1ba13e.async.js:1:5053426
    at _l (umi.cdcf4f80.js:1:1548033)
    at Kc (umi.cdcf4f80.js:1:1567239)
    at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
    at li (umi.cdcf4f80.js:1:1509384)
    at Wc (umi.cdcf4f80.js:1:1566990)
    at Cc (umi.cdcf4f80.js:1:1558536)
    at umi.cdcf4f80.js:1:1509675
```

**Comment by Baoyuantop** [comment]
> goto url `plugin/market`
> 
> show some plugins quickly then they disappear and the page got blank
> 
> dashboard_version | 3.0.0
> 
> ```
> 
> ﻿
> umi.cdcf4f80.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Plugin__List.c1fae2a6.async.js:1 
>  Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes. Please see https://github.com/microsoft/monaco-editor#faq
> p__Plugin__List.c1fae2a6.async.js:1 
>  You must define a function MonacoEnvironment.getWorkerUrl or MonacoEnvironment.getWorker
> 29
> 109.5c8c6f3a.async.js:1 
>  Error: Unexpected usage
>     at e.value (p__Plugin__List.c1fa…6.async.js:1:482931)
>     at p__Plugin__List.c1fa…6.async.js:1:496298
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> p__Route__List.0efb348d.async.js:1 
> Object
> web-client-content-script.js:1 
>  Uncaught TypeError: Cannot read properties of undefined (reading 'id')
>     at web-client-content-script.js:1:281387
>     at Array.every (<anonymous>)
>     at web-client-content-script.js:1:281359
> umi.cdcf4f80.js:1 
>  TypeError: Cannot read properties of undefined (reading 'disable')
>     at p__Plugin__PluginMar….async.js:1:3664285
>     at Array.filter (<anonymous>)
>     at p__Plugin__PluginMar….async.js:1:3664176
>     at _l (umi.cdcf4f80.js:1:1548033)
>     at Kc (umi.cdcf4f80.js:1:1567239)
>     at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
>     at li (umi.cdcf4f80.js:1:1509384)
>     at Wc (umi.cdcf4f80.js:1:1566990)
>     at Cc (umi.cdcf4f80.js:1:1558536)
>     at umi.cdcf4f80.js:1:1509675
> p__Plugin__PluginMar…187e4219.async.js:1 
>  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'disable')
>     at p__Plugin__PluginMar….async.js:1:3664285
>     at Array.filter (<anonymous>)
>     at p__Plugin__PluginMar….async.js:1:3664176
>     at _l (umi.cdcf4f80.js:1:1548033)
>     at Kc (umi.cdcf4f80.js:1:1567239)
>     at t.unstable_runWithPriority (umi.cdcf4f80.js:1:39456)
>     at li (umi.cdcf4f80.js:1:1509384)
>     at Wc (umi.cdcf4f80.js:1:1566990)
>     at Cc (umi.cdcf4f80.js:1:1558536)
>     at umi.cdcf4f80.js:1:1509675
> ```

Can you provide the configuration data in your etcd?

**Comment by juzhiyuan** [comment]
Hi, we will release a new dashboard to address legacy issues. Refer to https://github.com/apache/apisix-dashboard/issues/2981
