### ISSUE TITLE
使用dashboard 3.0.1打开插件页面空白

### ISSUE THREAD

**Issue by jinjianming** [apache/apisix-dashboard#2820]
### Issue description

Console error
```
umi.7de77dbe.js:1 TypeError: Cannot read properties of null (reading 'find')
    at cj (p__Plugin__List.86b10e9e.async.js:1:3479849)
    at pa (umi.7de77dbe.js:1:1522498)
    at Dl (umi.7de77dbe.js:1:1569170)
    at Uc (umi.7de77dbe.js:1:1561859)
    at Dc (umi.7de77dbe.js:1:1561784)
    at Cc (umi.7de77dbe.js:1:1558647)
    at umi.7de77dbe.js:1:1509712
    at t.unstable_runWithPriority (umi.7de77dbe.js:1:39456)
    at li (umi.7de77dbe.js:1:1509421)
    at fi (umi.7de77dbe.js:1:1509657)
bl @ umi.7de77dbe.js:1
```
**Is it not compatible with Apisix 3.2.1**

### Expected behavior

x

### How to Reproduce

`http://ip:80/plugin/list`

### Screenshots

![image](https://github.com/apache/apisix-dashboard/assets/57084209/18cb119b-406b-455c-92ff-182139f0ee93)

### Environment

- apisix version (cmd: `apisix version`): 3.2.1
- OS (cmd: `uname -a`):
- OpenResty / Nginx version (cmd: `nginx -V` or `openresty -V`):
- etcd version, if have (cmd: run `etcd --version`):
- apisix-dashboard version, if have:
- Browser version, if have:

**Comment by karl-chanel** [comment]
I experienced the same problem.

**Comment by zimbres** [comment]
Check if the plugin list is present on configuration


```
        plugins:
          - api-breaker
          - authz-keycloak
          - basic-auth
          - batch-requests
          - consumer-restriction
          - cors
          # - dubbo-proxy
          - echo
          # - error-log-logger
          # - example-plugin
          - fault-injection
          - grpc-transcode
          - hmac-auth
          - http-logger
          - ip-restriction
          - jwt-auth
          - kafka-logger
          - key-auth
          - limit-conn
          - limit-count
          - limit-req
          # - log-rotate
          # - node-status
          - openid-connect
          - prometheus
          - proxy-cache
          - proxy-mirror
          - proxy-rewrite
          - redirect
          - referer-restriction
          - request-id
          - request-validation
          - response-rewrite
          - serverless-post-function
          - serverless-pre-function
          # - skywalking
          - sls-logger
          - syslog
          - tcp-logger
          - udp-logger
          - uri-blocker
          - wolf-rbac
          - zipkin
          - server-info
          - traffic-split
```

**Comment by jinjianming** [comment]
![image](https://github.com/apache/apisix-dashboard/assets/57084209/1bee4077-303d-4688-b5dc-ac04a4e98e47)
```
    plugins:    # plugin list
      - api-breaker
      - authz-casbin
      - authz-casdoor
      - authz-keycloak
      - aws-lambda
      - azure-functions
      - basic-auth
      - clickhouse-logger
      - client-control
      - consumer-restriction
      - cors
      - csrf
      - datadog
      - echo
      - error-log-logger
      - ext-plugin-post-req
      - ext-plugin-post-resp
      - ext-plugin-pre-req
      - fault-injection
      - file-logger
      - forward-auth
      - google-cloud-logging
      - grpc-transcode
      - grpc-web
      - gzip
      - hmac-auth
      - http-logger
      - ip-restriction
      - jwt-auth
      - kafka-logger
      - kafka-proxy
      - key-auth
      - ldap-auth
      - limit-conn
      - limit-count
      - limit-req
      - loggly
      - mocking
      - opa
      - openid-connect
      - opentelemetry
      - openwhisk
      - prometheus
      - proxy-cache
      - proxy-control
      - proxy-mirror
      - proxy-rewrite
      - public-api
      - real-ip
      - redirect
      - referer-restriction
      - request-id
      - request-validation
      - response-rewrite
      - rocketmq-logger
      - server-info
      - serverless-post-function
      - serverless-pre-function
      - skywalking
      - skywalking-logger
      - sls-logger
      - splunk-hec-logging
      - syslog
      - tcp-logger
      - traffic-split
      - ua-restriction
      - udp-logger
      - uri-blocker
      - wolf-rbac
      - zipkin
      - elasticsearch-logge
      - openfunction
      - tencent-cloud-cls
      - ai
      - cas-auth
    plugin_attr:
      log-rotate:
        enable_compression: false
        max_kept: 3
        max_size: 10240
      prometheus:
        export_addr:
          ip: 0.0.0.0
```

**Comment by cdmonkey** [comment]
I experienced the same problem.

**Comment by BansheeLW** [comment]
I experienced the same problem.
I found that when requesting the interface "http://43.159.52.242:30080/apisix/admin/plugins?all=true", the returned response was empty, so the page reported an error and displayed a blank page. Why was the interface response empty?
<img width="931" alt="image" src="https://github.com/apache/apisix-dashboard/assets/15967345/786789bb-d58b-4a3f-b928-1cdac6d0543f">
<img width="1379" alt="image" src="https://github.com/apache/apisix-dashboard/assets/15967345/a0271525-55c7-4aac-b668-13e781aabdd2">

**Comment by andytael** [comment]
Experienced the same issue, downgrade to 3.0.0 image resolved the issue

**Comment by juzhiyuan** [comment]
Hi, we will release a new dashboard to address legacy issues. Refer to https://github.com/apache/apisix-dashboard/issues/2981
