### ISSUE TITLE
使用docker安装报错

### ISSUE THREAD

**Issue by CongGreat** [apache/apisix-dashboard#2911]
### Issue description

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca1613]

goroutine 1 [running]:
github.com/apisix/manager-api/internal/core/storage.InitETCDClient(0xc0005aba30?)
	/usr/local/apisix-dashboard/api/internal/core/storage/etcd.go:59 +0x53
github.com/apisix/manager-api/internal/core/server.(*server).setupStore(0x60?)
	/usr/local/apisix-dashboard/api/internal/core/server/store.go:27 +0x25
github.com/apisix/manager-api/internal/core/server.(*server).init(0x17c2801?)
	/usr/local/apisix-dashboard/api/internal/core/server/server.go:89 +0x52
github.com/apisix/manager-api/internal/core/server.(*server).Start(0xc0005a8dc8, 0xc000423ce0)
	/usr/local/apisix-dashboard/api/internal/core/server/server.go:49 +0x27
github.com/apisix/manager-api/cmd.manageAPI()
	/usr/local/apisix-dashboard/api/cmd/root.go:71 +0x91
github.com/apisix/manager-api/cmd.glob..func1(0x17b2940?, {0xf7f29c?, 0x0?, 0x0?})
	/usr/local/apisix-dashboard/api/cmd/root.go:40 +0x17
github.com/spf13/cobra.(*Command).execute(0x17b2940, {0xc000034250, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x17b2940)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/apisix/manager-api/cmd.Execute()
	/usr/local/apisix-dashboard/api/cmd/root.go:55 +0x25
main.main()
	/usr/local/apisix-dashboard/api/main.go:24 +0x17
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xca1613]

### Expected behavior

在docker中正常运行

### How to Reproduce

docker-compose -p docker-apisix -f docker-compose.yml up -d

[docker-compose.yml] 中的内容
dashboard:
    image: apache/apisix-dashboard:latest
    restart: always
    volumes:
      - ./dashboard_conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml:ro
    depends_on:
      - etcd
    ports:
      - "9000:9000/tcp"
    networks:
      apisix:

**Comment by Talbot3** [comment]
apisix-dashboard官方没有人维护了。你看看apisix-docker中都已经删除对这个库的引用示例了。

**Comment by CongGreat** [comment]
这是来自QQ邮箱的假期自动回复邮件。感谢您的来信，您的邮件我已收到，我将尽快回复您！

**Comment by hanqingwu** [comment]
@CongGreat , Pls check  dashboard_conf/conf.yaml  , how to config etcd endpoint  ?  And  can you check  etcd  whether health ?

**Comment by CongGreat** [comment]
这是来自QQ邮箱的假期自动回复邮件。感谢您的来信，您的邮件我已收到，我将尽快回复您！
