### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by ztgoto** [apache/apisix-dashboard#702]
Please answer these questions before submitting your issue.

- Why do you submit this issue?
- [x] Question or discussion
- [x] Bug
- [ ] Requirements
- [ ] Feature or performance improvement
- [ ] Other

___
### Question
- What do you want to know?
/apisix/admin/user/login
response 404 page not found
___
### Bug
- Which version of Apache APISIX Dashboard, OS, and Browser?
branch v2.0 build docker image

- What happened?
If possible, provide a way to reproduce the error.

___
### Requirements or improvement
- Please describe your requirements or improvement suggestions.
自己构建镜像各种问题，能不能直接在docker hub 上提供可用镜像

**Comment by juzhiyuan** [comment]
We will publish the docker image to Dockerhub once 2.0 is released.

**Comment by juzhiyuan** [comment]
`各种问题` means you are encountering Proxy issues? It would be better if you could provide some snapshots, so we could try to help you resolve them.

**Comment by ztgoto** [comment]
> `各种问题` means you are encountering Proxy issues? It would be better if you could provide some snapshots, so we could try to help you resolve them.

现有的tag 2.0-rc2 和master构建镜像时并不能成功，并不是代理或网络问题，而是lua脚本存在错误，这个已经被你们标记为bug。所以我不得不使用v2.0分支来构建镜像才能成功，可构建的镜像访问时并没有web界面，各种404，我也没有找到相关详细的文档说明

**Comment by membphis** [comment]
can you provide the error log? we need them.

**Comment by juzhiyuan** [comment]
> > `各种问题` means you are encountering Proxy issues? It would be better if you could provide some snapshots, so we could try to help you resolve them.
> 
> 现有的tag 2.0-rc2 和master构建镜像时并不能成功，并不是代理或网络问题，而是lua脚本存在错误，这个已经被你们标记为bug。所以我不得不使用v2.0分支来构建镜像才能成功，可构建的镜像访问时并没有web界面，各种404，我也没有找到相关详细的文档说明

ok, from your deeper description, I know you are using the master branch or 2.0 RC2 release.

Solution: use the latest codes from the v2.0 branch, not the 2.0 RC release. In the latest codes, we have fixed some errors related to Docker, please follow the docs in the README.

**Comment by juzhiyuan** [comment]
https://github.com/apache/apisix-dashboard/tree/v2.0#deployment

Here are the docs for 2.0, I'm sure we could build with it successfully.

**Comment by juzhiyuan** [comment]
I noticed you mentioned that `可构建的镜像访问时并没有web界面，各种404`, could you please provide some **snapshots**?

**Comment by ztgoto** [comment]
我确实是使用了/api/Dockerfile构建才导致没有web界面.使用根目录下的Dockerfile master分支也能构建成功。
但master /api/Dockerfile 确实存在问题，构建时错误如下
```
Step 13/17 : RUN  cd /go/manager-api/build-tools      && lua schema-sync.lua > /go/manager-api/schema.json      && cd /go/manager-api/      && rm -rf /go/manager-api/build-tools/
 ---> Running in f99c401d8f8b
lua: ./apisix/plugins/api-breaker.lua:24: attempt to index field 'shared' (a nil value)
stack traceback:
        ./apisix/plugins/api-breaker.lua:24: in main chunk
        [C]: in function 'require'
        schema-sync.lua:128: in main chunk
        [C]: ?
The command '/bin/sh -c cd /go/manager-api/build-tools      && lua schema-sync.lua > /go/manager-api/schema.json      && cd /go/manager-api/      && rm -rf /go/manager-api/build-tools/' returned a non-zero code: 1
```

我现在通过master 根目录Dockerfile构建成功的镜像却无法按照[文档](https://github.com/apache/apisix-dashboard/blob/v2.0/docs/deploy-with-docker.zh-CN.md) 中描述的那样启动
信息如下
```
docker run --network=host --rm -v /etc/apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml  imagenames

2020/11/06 01:30:14 [emerg] 1#1: host not found in upstream "manager" in /etc/nginx/conf.d/default.conf:36
nginx: [emerg] host not found in upstream "manager" in /etc/nginx/conf.d/default.conf:36
```

该项目文档的描述太过于简单了，也没有描述这块有需要nginx相关的配置

**Comment by juzhiyuan** [comment]
oh @ztgoto , sorry to lead your confused, please use the Dockerfile in the root folder[1]. As for the Dockerfile under the `/api` folder, @nic-chen @membphis do we really need this one? I'm not sure about this.

[1] https://github.com/apache/apisix-dashboard/blob/v2.0/Dockerfile

**Comment by juzhiyuan** [comment]
Please note, use the Dockerfile in the root folder (on the v2.0 branch).

https://github.com/apache/apisix-dashboard/blob/v2.0/Dockerfile

**Comment by ztgoto** [comment]
@juzhiyuan  我使用了分支v2.0根目录Dockerfile来构建镜像，虽然镜像成功构建，启动也正常。但构建过程中也有些错误(提示说可以忽略)，最后还是没有web界面(404 page not found) 我并不确定这个是不是由以下错误导致的
启动日志
```
#docker run --network=host --rm -v /etc/apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml apisix-dashboard:2.0
2020-11-06 02:48:11.124711 I | The Manager API is listening on 0.0.0.0:8999
```

构建日志
```
Step 19/31 : RUN yarn install
 ---> Running in 831d7574888f
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@api7-dashboard/plugin > @rjsf/antd@2.3.0" has unmet peer dependency "@babel/runtime-corejs2@^7.10.3".
warning "@api7-dashboard/plugin > @rjsf/antd@2.3.0" has unmet peer dependency "antd-dayjs-webpack-plugin@1.0.0".
warning "@api7-dashboard/plugin > @rjsf/antd@2.3.0" has unmet peer dependency "core-js@^2.5.7".
warning "@api7-dashboard/plugin > @uiw/react-codemirror@3.0.1" has unmet peer dependency "@babel/runtime@>=7.11.0".
warning "@api7-dashboard/plugin > @uiw/react-codemirror@3.0.1" has unmet peer dependency "codemirror@>=5.49.2".
warning "@api7-dashboard/pluginchart > styled-components@5.1.1" has unmet peer dependency "react-is@>= 16.8.0".
warning "@api7-dashboard/pluginchart > @mrblenny/react-flow-chart > react-zoom-pan-pinch@1.6.1" has unmet peer dependency "prop-types@^15.5.4".
warning " > @rjsf/antd@2.2.0" has unmet peer dependency "@babel/runtime-corejs2@^7.10.3".
warning " > @rjsf/antd@2.2.0" has unmet peer dependency "antd-dayjs-webpack-plugin@1.0.0".
warning " > @rjsf/antd@2.2.0" has unmet peer dependency "core-js@^2.5.7".
warning "@ant-design/pro-cli > @umijs/fabric > @typescript-eslint/eslint-plugin@3.10.1" has unmet peer dependency "@typescript-eslint/parser@^3.0.0".
warning "@umijs/plugin-blocks > @umijs/block-sdk > sylvanas > @umijs/fabric > @typescript-eslint/eslint-plugin@1.13.0" has incorrect peer dependency "@typescript-eslint/parser@^1.9.0".
warning "@umijs/plugin-blocks > @umijs/block-sdk > sylvanas > @umijs/fabric > eslint-config-airbnb@17.1.1" has incorrect peer dependency "eslint-plugin-react@^7.14.2".
warning "@umijs/plugin-esbuild > esbuild-webpack-plugin@1.0.5" has unmet peer dependency "webpack@^4.0.0".
warning "@umijs/preset-react > @umijs/plugin-layout@0.12.1" has incorrect peer dependency "@ant-design/pro-layout@^5.0.0".
warning "@umijs/preset-react > @umijs/plugin-dva > babel-plugin-dva-hmr@0.4.2" has unmet peer dependency "redbox-react@1.x".
warning "@umijs/preset-react > @umijs/plugin-dva > dva-loading@3.0.20" has unmet peer dependency "dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0".
warning "@umijs/preset-react > @umijs/plugin-dva > dva > connected-react-router@6.5.2" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
[5/5] Building fresh packages...
warning Error running install script for optional dependency: "/usr/local/apisix-dashboard/web/node_modules/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /usr/local/apisix-dashboard/web/node_modules/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.15.0 | linux | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if \"python\" can be used
gyp ERR! find Python - \"python\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python2\" can be used
gyp ERR! find Python - \"python2\" is not in PATH or produced an error
gyp ERR! find Python checking if \"python3\" can be used
gyp ERR! find Python - \"python3\" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python=\"/path/to/pythonexecutable\"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python \"/path/to/pythonexecutable\"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:315:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:327:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:465:16)
gyp ERR! stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
gyp ERR! System Linux 4.19.104-microsoft-standard
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /usr/local/apisix-dashboard/web/node_modules/node-pty
gyp ERR! node -v v14.15.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok"
info This module is OPTIONAL, you can safely ignore this error
```

**Comment by juzhiyuan** [comment]
@ztgoto 

1. The error message output when you are building the frontend is ok and safe to ignore, this is related to node-gyp and we don't need it, but some dependencies using them, so we choose to just ignore.

2. 

```
#docker run --network=host --rm -v /etc/apisix-dashboard/conf/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml apisix-dashboard:2.0
2020-11-06 02:48:11.124711 I | The Manager API is listening on 0.0.0.0:8999
```

This log means we have successfully run the dashboard with Docker, as we couldn't see the dashboard pages, I'm not sure if it's related to this PR[1] which was just merged? Let me check the latest codes. Give me 3 hours.

[1] https://github.com/apache/apisix-dashboard/commit/b4b646bac921e78520aee7dff4b63dff831c4aa0

**Comment by juzhiyuan** [comment]
@ztgoto Just checked and we are fixing the Docs & Deploy with Docker CD, once this PR[1] is merged, this issue could be marked as resolved.

[1] https://github.com/apache/apisix-dashboard/pull/701

**Comment by juzhiyuan** [comment]
We are working on this issue.

**Comment by membphis** [comment]
> oh @ztgoto , sorry to lead your confused, please use the Dockerfile in the root folder[1]. As for the Dockerfile under the `/api` folder, @nic-chen @membphis do we really need this one? I'm not sure about this.
> 
> [1] https://github.com/apache/apisix-dashboard/blob/v2.0/Dockerfile

I can not sure for this too. need your help ^_^ @nic-chen

**Comment by nic-chen** [comment]
the Dockerfile under the `/api` folder is used for e2e test, it need to run the newest code. @membphis @juzhiyuan

**Comment by membphis** [comment]
> the Dockerfile under the `/api` folder is used for e2e test, it need to run the newest code. @membphis @juzhiyuan

that is not a good way.

if it is used for E2E test, we should move this file to `test` folder.

**Comment by juzhiyuan** [comment]
Yes, or users will get confused.

**Comment by nic-chen** [comment]
fixed, we had CI to make sure page not 404 :
https://github.com/apache/apisix-dashboard/blob/v2.0/.github/workflows/deploy-with-docker.yml#L44
